api_gateway:
  http:
    host: "127.0.0.1"
    port: 8080
  services:
    auth:
      url: "http://127.0.0.1:8081"
    calc:
      url: "http://127.0.0.1:8082"
  router: "gorilla"
  logger: "zap"

auth:
  http:
    host: "127.0.0.1"
    port: 8081
    read_timeout: "15s"
    write_timeout: "15s"
  database:
    dsn: "file:data/auth.db?cache=shared&mode=rwc"
  jwt:
    secret: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30"
    access_token_expiry: "15m"
    refresh_token_expiry: "24h"
  logger: "zap"
  router: "gorilla"

calc:
  orchestrator:
    port: 8082
    time_addition_ms: 0
    time_subtraction_ms: 0
    time_multiplication_ms: 0
    time_division_ms: 0
  agent:
    workers: 4
    timeout: "5s"